persona:
  name: nan
  agent type: nan
  nationality: nan
  age: nan
  gender: nan
  relationship:
    - nan
  personality:
    - nan
  preference:
    - nan
  daily routine:
    - nan      
observable state:  
  clothes:
    - nan
  holding object:
    left hand: nan
    right hand: nan
  position:
    x: nan
    y: nan
  velocity:
    x: nan
    y: nan
  heading:
    theta: nan
  
internal state:
  high-level task: nan
  low-level task: nan
  action plan long:
    - nan
  action plan short:
    - nan
  target position:
    x: nan
    y: nan
  target heading:
    theta: nan
  

