name: nan
agent type: human
nationality: USA
age: nan
gender: nan

role: nan

daily routine:
 weekdays:
  - task: nan
    time: nan
  - task: nan
    time: nan
  - task: nan
    time: nan
  - task: nan
    time: nan
    
 weekend:
  - task: nan
    time: nan
  - task: nan
    time: nan
  - task: nan
    time: nan
  - task: nan
    time: nan
    
personality:
 - nan
 - nan
 - nan
      
Preference:
 - nan
 - nan
 - nan
      
clothes:
 - nan
 - nan
 - nan

